### ISSUE TITLE
Spikes aléatoires

### ISSUE THREAD

**Issue by Bichoff** [EPFL-SV-cpp-projects/neuro-2#29]

**Comment by rurishu** [comment]
Outil pour générer des nombres aléatoires
====================================================================
#include <iostream>
#include <random>
using namespace std;

int main() {
	
	random_device random_number;
	
	for (int i(0); i < 100; ++i) {		// creates for example, 100 random numbers
		cout << hex << random_number() << "\n";	// print the numbers, hexadecimal base
	}
	
	getchar();
	
	return 0;
}

**Comment by rurishu** [comment]
#include <iostream>
#include <random>

**Comment by rurishu** [comment]
iostream
random
