### ISSUE TITLE
CMake cross-platform

### ISSUE THREAD

**Issue by Kognefaure** [EPFL-SV-cpp-projects/neuro-2#56]
Un conflit entre GTest et le compilateur MinGW fait qu'on doit avoir un CMakeLists spécial pour pouvoir compiler sous Windows et MinGW.

La ligne suivante permet la compilation avec les systèmes Unix (Mac et Linux):

`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -pedantic -std=c++11")`

Pour Windows/MinGW, il faut la remplacer par 2 lignes:

```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -pedantic -std=gnu++11")
add_definitions(-DWINVER=0x500)
```

Modifier le CMakeLists.txt pour qu'il détecte quel est le système de l'ordinateur et utilise les bonnes commandes. Il faudra faire quelques recherches pour trouver comment identifier si le système est Windows.

**Comment by vformaz** [comment]
J'ai trouvé quelque chose mais le problème reste le même il ne compile toujours pas après 54% pour les mêmes raisons. Pourtant sur les forums, ils disent que cette notation devrait suffir à détecter la plateforme.
if (WIN32)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -pedantic -std=gnu++11")
add_definitions(-DWINVER=0x500)
endif(WIN32)
if(Unix)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -pedantic -std=c++11")
set(CMAKE_INCLUDE_CURRENT_DIR ON)
endif()

**Comment by Kognefaure** [comment]
Je ne connais pas trop les "if" dans CMake mais ça me paraît bizarre qu'il y ait un paramètre dans le premier _endif_ et pas le deuxième. 

Dans tous les cas c'est plus sûr de faire avec un if-else. On peut rajouter la commande "message" pour vérifier que CMake a bien trouvé la bonne version (ça s'affiche dans l'interface au moment de faire Configure).

```
if (WIN32)
  message("Compiling for Windows")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -pedantic -std=gnu++11")
  add_definitions(-DWINVER=0x500)
else()
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -pedantic -std=c++11")
  set(CMAKE_INCLUDE_CURRENT_DIR ON)
endif()
```

Avant de refaire Configure/Generate, tente de supprimer le cache aussi pour être sûr de bien tenir compte des modifs (dans l'interface de CMake, c'est "File -> Delete cache" en haut à gauche).

**Comment by vformaz** [comment]
J'ai modifié le if/else mais je suis pas sûr que ça change grand chose.  Avec un message je vois qu'il rentre dans le if du windows, mais toujours le même problème avec make (même en vidant le cache).

**Comment by Kognefaure** [comment]
C'est les options qui ont fait que ça marche chez @camillehyde et moi. Il doit y avoir une différence de configuration chez toi.

Lance le programme "MinGW installer", et cherche les trois options que j'ai mis en rouge sur l'image:

![mingw_threads](https://cloud.githubusercontent.com/assets/5493792/20859728/52f13028-b967-11e6-836e-76f2a7f0c4dd.png)

S'il y en a qui sont pas cochés, clique sur chacun d'eux et fais "Mark for installation". Ensuite en haut à gauche, choisis "Installation -> Apply changes" et "Apply" sur la fenêtre qui s'ouvre.

Je croise les doigts.

**Comment by vformaz** [comment]
Malheureusement ça ne change pas mon erreur. Le problème c'est d'être sûr que les problèmes de configuration vont être régler sur les machines de l'epfl. Du coup, il faut savoir si c'est le bel et bien la configuration ou bien le code qui doit être modifié (le code de cmake)
