### ISSUE TITLE
Ajustement potentiel

### ISSUE THREAD

**Issue by Kognefaure** [EPFL-SV-cpp-projects/neuro-2#60]
Les potentiels envoyés par le Background sont trop faibles; les neurones de l'environnement ne parviennent pas à envoyer de spikes.

Revoir l'équation pour le calcul des potentiels. 

(En rapport avec ça: corriger le calcul de la distribution de poisson. La classe utilisée renvoie toujours le même chiffre, il faut simplement l'initialiser une unique fois dans le code et pas à chaque incrémentation de temps t)

**Comment by Bichoff** [comment]
Pou l'équation, ça marche je l'ai fait mais j'ai pas mis sur git parce j'arrive pas à initialiser le fénérateur de nombre aléatoire dans le constructeur de env. Comment faut-il faire ?

**Comment by Bichoff** [comment]
J'ai mis le générateur et le nombre moyen dans le constructeur de env :" std::default_random_engine generator; et std::poisson_distribution<int> distribution(v_ext*excitatory_connection)"
Et j'ai laissé l'appel de nombres dans random spike, mais comment faire pour qu'il sache qu'on a initialisé un générateur dans le constructeur de env ?

**Comment by Kognefaure** [comment]
Il faudrait les mettre comme variables globales, donc sous la partie "private" de Env.h.

Du coup l'initialisation dans le constructeur doit aussi être légèrement modifiée.

**Comment by Bichoff** [comment]
j'ai essayé, mais il me dit que "std::default_random_engine" et "std::poisson_distribution" ne sont pas des types de variable ...

**Comment by Kognefaure** [comment]
Il doit manquer la librairie pour ces classes.

A rajouter en haut de Env.hpp: #include <random>

**Comment by Bichoff** [comment]
oui j'ai oublié la librairie ... Merci !
