### ISSUE TITLE
Script python: gestion complète

### ISSUE THREAD

**Issue by Kognefaure** [EPFL-SV-cpp-projects/neuro-2#61]
Il y a deux points à régler avec le script en python pour le rendu graphique:

- comme ce n'est pas un fichier C++, CMake ne le prend pas en charge. Il n'est pas transféré dans le dossier build/ et n'est donc pas utilisé dans le programme. Modifier le CMakeLists.txt pour indiquer que le script python doit être copié dans le dossier build/. Une piste possible est la fonction **file()** de CMake: http://stackoverflow.com/questions/697560/how-to-copy-directory-from-source-tree-to-binary-tree

- Si python n'est pas installé sur l'ordinateur de l'utilisateur, le programme s'exécute jusqu'au moment du rendu graphique, où il crash. L'idéal serait de détecter si python est installé au début de la fonction main(), et d'arrêter le programme avec un message d'erreur propre. La fonction **system()** de C++ et sa valeur de retour peut permettre de régler ceci facilement.

**Comment by Kognefaure** [comment]
@vformaz J'ai trouvé un truc plus précis pour python. La commande suivante:

` python -c "import matplotlib"`

Devrait renvoyer "0" avec **system()** si la librairie matplotlib est installée, ou renvoyer une erreur. 

Sinon je sais pas du tout pourquoi la commande "python" ne fait rien chez toi. D'après ce que j'ai vu, les commandes "py" et "python" sont équivalentes, elles devraient toujours être disponible...

**Comment by vformaz** [comment]
quelque chose du style : sytem("python -c "import matplotlib"")=0 ? je suis pas sûr de comprendre comment s'utilise du coup la commande. La commande qu'on donnerait dans le terminal passé en string dans la fonction système ?

**Comment by Kognefaure** [comment]
C'est juste. Je crois. Pas sûr d'avoir compris ta question ^^ je reprends.
**system("_commande_")** va exécuter _commande_ de la même manière que quand tu le fais dans le terminal. La valeur de retour de **system()** est 0 si la commande n'a pas eu d'erreur.
Donc effectivement, à l'intérieur de **system()** il suffit de passer en string la commande que je t'ai passée.

Petit détail en plus maintenant que tu postes ta ligne: pour mettre des guillemets dans un string, il faut le "parer" avec \ :

`system("python -c \"import matplotlib\"")`

au lieu de

`system("python -c \"import matplotlib\"")`

**Comment by Kognefaure** [comment]
Après la remarque de Charlotte dans #64 : la commande FILE() du CMakeLists n'est pas appropriée, il faut utiliser configure_file(): http://stackoverflow.com/questions/34799916/cmake-copy-file-from-source-directory-to-binary-directory

(Dans la réponse officielle, le paramètre <input> est relatif à la racine neuro-2/, et le dossier <output> relatif au dossier build/. Donc il faut utiliser les même noms de fichier que pour file()).

**Comment by vformaz** [comment]
D'acc je modifie tout ça
